{-|
  Hack to get idris modules that depend on the autogenerated Paths_idris to work inside
  AN.

  Basically, when compiling with cabal or stack, an autogenerated module in the form
  Paths_${project_name} is created. Si
 -}
module Paths_idris (
    version,
    getBinDir, getLibDir, getDataDir, getLibexecDir,
    getDataFileName, getSysconfDir
  ) where

import Paths_AN201710
