{-|
  Hack to get idris modules that depend on the autogenerated Version_idris to work inside
  AN.

  Basically, when compiling with cabal or stack, an autogenerated module in the form
  Version_${project_name} is created. Si
 -}
module Version_idris(gitHash) where

import Version_AN201710

